- name: Onboarding - Générer nom et créer inventaire AD
  hosts: localhost
  gather_facts: no

  vars:
    ldap_server: "ldap://192.168.10.4"
    ldap_user: "ansible@fonteynethekitchen.local"
    ldap_password: "motdepasse"
    ldap_base: "dc=fonteynethekitchen,dc=local"

    departement: "IT"
    type_machine: "LAPTOP"
    inventaire_path: "./inventaire_ad.ini"

  tasks:
    - name: Interroger l'AD pour obtenir les noms d'ordinateurs
      shell: |
        ldapsearch -x -H "{{ ldap_server }}" -D "{{ ldap_user }}" -w "{{ ldap_password }}" \
        -b "{{ ldap_base }}" "(objectClass=computer)" name | grep '^name:' | awk '{print $2}'
      register: ldap_output

    - name: Extraire les noms existants
      set_fact:
        noms_machines_ad: "{{ ldap_output.stdout_lines | map('regex_replace', '^name: ', '') | list }}"

    - name: Générer contenu de l'inventaire
      copy:
        dest: "{{ inventaire_path }}"
        content: |
          [ad_computers]
          {% for name in noms_machines_ad %}
          {{ name }}.fonteynethekitchen.local
          {% endfor %}

    - name: Filtrer les noms déjà utilisés pour ce type/département
      set_fact:
        prefix: "{{ departement }}-{{ type_machine }}"
        existants: "{{ noms_machines_ad | select('match', '^' ~ prefix ~ '-\\d{3}$') | list }}"

    - name: Extraire numéros existants
      set_fact:
        existants_ids: >-
          {{ existants | map('regex_replace', '^' ~ prefix ~ '-(\\d{3})$', '\\1') | map('int') | list }}

    - name: Générer le prochain numéro libre
      set_fact:
        next_id: >-
          {% set ids = existants_ids | sort %}
          {% set found = 0 %}
          {% for i in range(1, 1000) %}
            {% if i not in ids and found == 0 %}
              {{ '%03d' % i }}
              {% set found = 1 %}
            {% endif %}
          {% endfor %}

    - name: Créer nom disponible
      set_fact:
        new_hostname: "{{ prefix }}-{{ next_id }}"

    - name: Afficher le nom généré
      debug:
        msg: "Nom généré disponible : {{ new_hostname }}"
