- name: Onboarding - Générer un nom unique et créer inventaire AD
  hosts: localhost
  gather_facts: no

  vars:
    ldap_server: "ldap://192.168.10.4"
    ldap_user: "ansible@fonteynethekitchen.local"
    ldap_password: "motdepasse"
    ldap_base: "dc=fonteynethekitchen,dc=local"
    inventaire_path: "/tmp/inventaire_ad.ini"
    departement: "IT"
    type_machine: "LAPTOP"

  tasks:
    - name: Interroger l'AD pour obtenir les noms d'ordinateurs
      shell: |
        ldapsearch -x -H "{{ ldap_server }}" -D "{{ ldap_user }}" -w "{{ ldap_password }}" \
        -b "{{ ldap_base }}" "(objectClass=computer)" name | grep '^name:' | cut -d' ' -f2
      register: ldap_output

    - name: Extraire et filtrer les noms
      set_fact:
        noms_machines_ad: "{{ ldap_output.stdout_lines | reject('equalto', '') | list }}"

    - name: Afficher les noms détectés dans l'AD
      debug:
        var: noms_machines_ad

    - name: Définir le préfixe de nom
      set_fact:
        prefix: "{{ departement }}-{{ type_machine }}"

    - name: Extraire uniquement les noms correspondant au modèle
      set_fact:
        existants: "{{ noms_machines_ad | select('match', '^' ~ prefix ~ '-\\d{3}$') | list }}"

    - name: Extraire les IDs utilisés
      set_fact:
        existants_ids: "{{ existants | map('regex_replace', '^' ~ prefix ~ '-(\\d{3})$', '\\1') | map('int') | list }}"

    - name: Trouver le plus petit ID libre
      set_fact:
        next_id: >-
          {% set ids = existants_ids | sort %}
          {% for i in range(1, 1000) %}
            {% if i not in ids %}
              {{ '%03d' % i }}
              {% break %}
            {% endif %}
          {% endfor %}

    - name: Générer le nom unique
      set_fact:
        new_hostname: "{{ prefix }}-{{ next_id }}"

    - name: Afficher le nom généré
      debug:
        msg: "Nom disponible généré : {{ new_hostname }}"

    - name: Générer le fichier d'inventaire
      copy:
        dest: "{{ inventaire_path }}"
        content: |
          [ad_computers]
          {% for name in noms_machines_ad %}
          {{ name }}.fonteynethekitchen.local
          {% endfor %}

    - name: Afficher les lignes ajoutées à l'inventaire
      debug:
        msg: |
          Contenu écrit dans {{ inventaire_path }} :
          [ad_computers]
          {% for name in noms_machines_ad %}
          {{ name }}.fonteynethekitchen.local
          {% endfor %}
