- name: Joindre un poste Windows au domaine (sans OU spécifique)
  hosts: onboarding
  gather_facts: yes

  tasks:
    - name: Lire le département depuis le fichier texte
      ansible.windows.win_shell: Get-Content -Path 'C:\\departement.txt'
      register: departement_raw

    - name: Nettoyer la chaîne lue
      set_fact:
        departement: "{{ departement_raw.stdout | trim }}"

    - name: Joindre la machine au domaine (dans l’OU par défaut)
      ansible.windows.win_domain_membership:
        dns_domain_name: fonteynethekitchen.local
        domain_admin_user: "{{ ldap_user }}"
        domain_admin_password: "{{ ldap_password }}"
        hostname: "{{ ansible_hostname }}"
        state: domain
      register: domain_join

    - name: Reboot si nécessaire après le join
      ansible.windows.win_reboot:
      when: domain_join.reboot_required

    - name: Afficher un résumé clair
      debug:
        msg: "✅ Machine jointe au domaine fonteynethekitchen.local avec le nom {{ ansible_hostname }}"

    - name: Reboot forcé final pour déconnecter l’utilisateur local
      ansible.windows.win_reboot:
        msg: "Reboot final après le join pour basculer en session domaine"
        reboot_timeout: 600
