- name: LDAP
  hosts: localhost
  gather_facts: no

  tasks:
    - name: Voir la sortie brute de ldapsearch
      shell: >
        ldapsearch -x -H "{{ ldap_server }}"
        -D "{{ ldap_user }}"
        -w "{{ ldap_password }}"
        -b "{{ ldap_base }}"
        "(objectClass=computer)"
        name
      register: ldap_raw

    - name: Afficher la sortie brute LDAP
      debug:
        var: ldap_raw.stdout
    - name: Extraire les noms depuis la sortie brute
      set_fact:
        noms_machines_ad: >-
          {{ ldap_raw.stdout.split('\n') | select('match', '^name:') | map('regex_replace', '^name: ', '') | list }}
    - name: Afficher les noms extraits
      debug:
        var: noms_machines_ad
