---
- name: Onboarding automatique depuis fichier texte
  hosts: onboarding
  gather_facts: yes

  vars:
    inventaire_path: "/tmp/semaphore/inventaire_ad.ini"
    prefix_map:
      IT:  "IT-LAPTOP"
      HR:  "HR-LAPTOP"
      FIN: "FIN-LAPTOP"
      COM: "COM-LAPTOP"

  tasks:
    # ------------------------------------------------------------------
    # 1) Département du poste Windows
    # ------------------------------------------------------------------
    - name: Lire le département
      ansible.windows.win_shell: Get-Content -Path 'C:\\departement.txt'
      register: departement_raw

    - name: Nettoyer et valider
      set_fact:
        departement: "{{ departement_raw.stdout | trim }}"
      failed_when: departement not in prefix_map
      msg: "Département « {{ departement }} » non reconnu"

    # ------------------------------------------------------------------
    # 2) Charger une seule fois l’inventaire (localhost)
    # ------------------------------------------------------------------
    - name: Charger l’inventaire
      slurp:
        src: "{{ inventaire_path }}"
      register: inventaire_slurp
      ignore_errors: yes               # 1ʳᵉ exécution : fichier absent OK
      delegate_to: localhost
      vars:
        ansible_connection: local
      run_once: true

    - name: Distribuer le contenu à tous les hôtes
      add_host:
        name: "{{ item }}"
        inventaire_content_b64: "{{ inventaire_slurp.content | default('') }}"
      loop: "{{ ansible_play_hosts }}"
      delegate_to: localhost
      vars:
        ansible_connection: local
      run_once: true

    # ------------------------------------------------------------------
    # 3) Déterminer le prochain hostname disponible
    # ------------------------------------------------------------------
    - name: Extraire les noms connus
      set_fact:
        existants: >-
          {{
            inventaire_content_b64
            | b64decode | split('\n')
            | reject('match', '^\[.*\]')
            | reject('equalto', '')
            | map('regex_replace', '\..*$', '')
            | select('match', '^' ~ prefix_map[departement] ~ '-\d{3}$')
            | list
          }}

    - name: IDs déjà pris
      set_fact:
        existants_ids: "{{ existants | map('regex_replace','^.*-(\\d{3})$','\\1') | map('int') | list }}"

    - name: Prochain ID libre
      set_fact:
        next_id: "{{ '%03d' % ((range(1,1000) | difference(existants_ids)) | min) }}"

    - name: Nouveau nom d’hôte
      set_fact:
        new_hostname: "{{ prefix_map[departement] }}-{{ next_id }}"

    - debug:
        msg: "Nom à appliquer : {{ new_hostname }}"

    # ------------------------------------------------------------------
    # 4) Renommer la machine + reboot si nécessaire
    # ------------------------------------------------------------------
    - name: Appliquer le nom
      ansible.windows.win_hostname:
        name: "{{ new_hostname }}"
      register: rename_result

    - ansible.windows.win_reboot:
      when: rename_result.changed

    # ------------------------------------------------------------------
    # 5) Mettre à jour l’inventaire (une seule fois, localhost)
    # ------------------------------------------------------------------
    - name: Ajouter le nom dans l’inventaire
      copy:
        dest: "{{ inventaire_path }}"
        content: |
          [ad_computers]
          {% for name in (existants + [new_hostname]) | unique | sort %}
          {{ name }}.fonteynethekitchen.local
          {% endfor %}
      when: new_hostname not in existants
      delegate_to: localhost
      vars:
        ansible_connection: local
      run_once: true

    - debug:
        msg: "Inventaire mis à jour avec {{ new_hostname }}"
      when: new_hostname not in existants
      run_once: true
