---
- name: Onboarding automatique depuis fichier texte
  hosts: onboarding
  gather_facts: yes

  vars:
    inventaire_path: "/tmp/semaphore/inventaire_ad.ini"
    fqdn_suffix: ".fonteynethekitchen.local"

    prefix_map:
      IT:  "IT-LAPTOP"
      HR:  "HR-LAPTOP"
      FIN: "FIN-LAPTOP"
      COM: "COM-LAPTOP"

  tasks:
  ###################################################################
  # 0) Charger l’inventaire (une seule fois) et le partager
  ###################################################################
  - name: Charger l'inventaire (peut être absent)
    slurp:
      src: "{{ inventaire_path }}"
    register: inventaire_slurp
    ignore_errors: true
    delegate_to: localhost
    run_once: true

  - name: Partager le contenu base64 à tous les hôtes
    set_fact:
      inventaire_b64_global: "{{ inventaire_slurp.content | default('') }}"
    delegate_to: localhost
    delegate_facts: true
    run_once: true

  ###################################################################
  # 1) Lire et valider le département
  ###################################################################
  - name: Lire le département
    ansible.windows.win_shell: Get-Content -Path 'C:\\departement.txt'
    register: departement_raw

  - set_fact:
      departement: "{{ departement_raw.stdout | trim }}"

  - fail:
      msg: "Département « {{ departement }} » non reconnu"
    when: departement not in prefix_map

  ###################################################################
  # 2) Construire la liste des lignes du .ini et calculer le prochain nom
  ###################################################################
  - name: Mettre inventaire_lignes à liste vide
    set_fact:
      inventaire_lignes: []

  - name: Décoder l'inventaire s'il existe
    set_fact:
      inventaire_lignes: "{{ (hostvars['localhost'].inventaire_b64_global | b64decode).split('\n') }}"
    when: hostvars['localhost'].inventaire_b64_global | length > 0

  - name: Toutes les lignes hostnames
    set_fact:
      inventaire_hostnames: >-
        {{
          inventaire_lignes
          | reject('match', '^\\[.*\\]')
          | reject('equalto', '')
          | list
        }}

  - name: Noms existants du même département
    set_fact:
      existants_dep: >-
        {{
          inventaire_hostnames
          | map('regex_replace', '\\..*$', '')
          | select('match', '^' ~ prefix_map[departement] ~ '-\\d{3}$')
          | list
        }}

  - name: IDs déjà pris (dans ce département)
    set_fact:
      existants_ids: "{{ existants_dep
                        | map('regex_replace', '^.*-(\\d{3})$', '\\1')
                        | map('int')
                        | list }}"

  - name: Prochain ID libre
    set_fact:
      next_id: "{{ '%03d' % ((range(1,1000) | difference(existants_ids)) | min) }}"

  # --- correctif : deux set_fact séparés -----------------------------
  - name: Définir le nouveau hostname
    set_fact:
      new_hostname: "{{ prefix_map[departement] }}-{{ next_id }}"

  - name: Construire le FQDN complet
    set_fact:
      new_fqdn: "{{ new_hostname }}{{ fqdn_suffix }}"

  - debug:
      msg: "Nom à appliquer : {{ new_hostname }}"

  ###################################################################
  # 3) Renommer le PC Windows + reboot
  ###################################################################
  - name: Appliquer le nom
    ansible.windows.win_hostname:
      name: "{{ new_hostname }}"
    register: rename_result

  - ansible.windows.win_reboot:
    when: rename_result.changed

  ###################################################################
  # 4) Ajouter la ligne dans l’inventaire (si absente)
  ###################################################################
  - name: S’assurer que la section [ad_computers] existe
    lineinfile:
      path: "{{ inventaire_path }}"
      line: "[ad_computers]"
      state: present
      create: yes
    delegate_to: localhost
    connection: local
    run_once: true

  - name: Ajouter le FQDN dans l’inventaire
    lineinfile:
      path: "{{ inventaire_path }}"
      line: "{{ new_fqdn }}"
      insertafter: "^\\[ad_computers\\]$"
      state: present
    when: new_fqdn not in inventaire_hostnames
    delegate_to: localhost
    connection: local
    run_once: true

  - debug:
      msg: "Inventaire mis à jour avec {{ new_fqdn }}"
    when: new_fqdn not in inventaire_hostnames
    run_once: true
