---
#############################################################################
# Onboarding poste Windows : renommage + logiciels + inventaire AD
#############################################################################
- name: Onboarding automatique poste Windows
  hosts: onboarding
  gather_facts: yes
  collections:
    - ansible.windows
    - community.windows

  vars:
    inventaire_path: "/tmp/semaphore/inventaire_ad.ini"
    fqdn_suffix: ".fonteynethekitchen.local"

    prefix_map:
      Achat:                    "ACH-LAPTOP"
      Comptabilité:             "COMPT-LAPTOP"
      Direction:                "DIR-LAPTOP"
      Facility:                 "FAC-LAPTOP"
      Finance:                  "FIN-LAPTOP"
      Formation:                "FOR-LAPTOP"
      IT:                       "IT-LAPTOP"
      Livraison:                "LIV-LAPTOP"
      Marketing:                "MKT-LAPTOP"
      Production:               "PROD-LAPTOP"
      "Qualité":                "QUAL-LAPTOP"
      "Responsable Production": "RESP-LAPTOP"
      "Student/Stagiaire":      "STG-LAPTOP"
      Testing:                  "TST-LAPTOP"
      Vente:                    "VNT-LAPTOP"

    software_map:
      Achat: [googlechrome, opera, firefox, notepadplusplus, 7zip, greenshot, 1password, vlc, zoom, microsoft-teams]
      Comptabilité: [googlechrome, opera, firefox, notepadplusplus, 7zip, greenshot, 1password, vlc, zoom, microsoft-teams]
      Direction: [googlechrome, opera, firefox, notepadplusplus, 7zip, greenshot, 1password, vlc, zoom, microsoft-teams]
      Facility: [googlechrome, opera, firefox, notepadplusplus, 7zip, greenshot, 1password, vlc, zoom, microsoft-teams]
      Finance: [googlechrome, opera, firefox, notepadplusplus, 7zip, greenshot, 1password, vlc, zoom, microsoft-teams]
      Formation: [googlechrome, opera, firefox, notepadplusplus, 7zip, greenshot, 1password, vlc, zoom, microsoft-teams]
      IT: [teamviewer, mobaxterm, notepadplusplus, vscode, googlechrome, opera, firefox,
           virtualbox, putty, filezilla, 7zip, winrar, git, greenshot, discord, openvpn, googledrive,
           angryip, advanced-ip-scanner, 1password, rufus, obs-studio, shotcut, foxitreader, keepass, vlc, zoom, microsoft-teams, libreoffice-fresh, python, sadp]
      Livraison: [googlechrome, opera, firefox, notepadplusplus, 7zip, greenshot, 1password, vlc, zoom, microsoft-teams]
      Marketing: [googlechrome, opera, firefox, notepadplusplus, 7zip, greenshot, 1password, vlc, zoom, microsoft-teams]
      Production: [googlechrome, opera, firefox, notepadplusplus, 7zip, greenshot, 1password, vlc, zoom, microsoft-teams]
      "Qualité": [googlechrome, opera, firefox, notepadplusplus, 7zip, greenshot, 1password, vlc, zoom, microsoft-teams]
      "Responsable Production": [googlechrome, opera, firefox, notepadplusplus, 7zip, greenshot, 1password, vlc, zoom, microsoft-teams]
      "Student/Stagiaire": [googlechrome, opera, firefox, notepadplusplus, 7zip, greenshot, 1password, vlc, zoom, microsoft-teams]
      Testing: [googlechrome, opera, firefox, notepadplusplus, 7zip, greenshot, 1password, vlc, zoom, microsoft-teams]
      Vente: [googlechrome, opera, firefox, notepadplusplus, 7zip, greenshot, 1password, vlc, zoom, microsoft-teams]


  ###################################################################
  # 0) Charger l’inventaire (une seule fois)
  ###################################################################
  tasks:
    - name: Lire le fichier inventaire (vide si absent)
      set_fact:
        inventaire_txt: "{{ lookup('file', inventaire_path, errors='ignore') | default('') }}"
      delegate_to: localhost
      delegate_facts: true
      run_once: true
      vars:
        ansible_connection: local

  ###################################################################
  # 1) Département
  ###################################################################
    - name: Lire le département
      ansible.windows.win_shell: Get-Content -Path 'C:\\departement.txt'
      register: departement_raw

    - set_fact:
        departement: "{{ departement_raw.stdout | trim }}"

    - fail:
        msg: "Département « {{ departement }} » non reconnu"
      when: departement not in prefix_map

  ###################################################################
  # 2) Calcul du prochain hostname
  ###################################################################
    - name: Lignes déjà présentes
      set_fact:
        inventaire_hostnames: "{{ hostvars['localhost'].inventaire_txt.splitlines()
                                  | reject('match', '^\\s*\\[.*\\]')
                                  | reject('equalto', '')
                                  | list }}"

    - name: Noms du même département
      set_fact:
        existants_dep: "{{ inventaire_hostnames
                          | map('regex_replace', '\\..*$', '')
                          | select('match', '^' ~ prefix_map[departement] ~ '-\\d{3}$')
                          | list }}"

    - name: IDs déjà pris
      set_fact:
        existants_ids: "{{ existants_dep
                          | map('regex_replace', '^.*-(\\d{3})$', '\\1')
                          | map('int')
                          | list }}"

    # 1️⃣ compute the number only
    - name: Compute next_id
      set_fact:
        next_id: "{{ '%03d' % ((range(1, 1000) | difference(existants_ids)) | min) }}"
    
    # 2️⃣ build the derived strings that depend on it
    - name: Build new host identifiers
      set_fact:
        new_hostname: "{{ prefix_map[departement] }}-{{ next_id }}"
        new_fqdn: "{{ prefix_map[departement] }}-{{ next_id }}{{ fqdn_suffix }}"

    - debug:
        msg: "→ Nouveau nom : {{ new_hostname }}"

  ###################################################################
  # 3) Renommer + reboot
  ###################################################################
    - name: Appliquer le nouveau nom
      ansible.windows.win_hostname:
        name: "{{ new_hostname }}"
      register: rename_result

    - name: Redémarrer si le nom a changé
      ansible.windows.win_reboot:
      when: rename_result.changed

  ###################################################################
  # 4) Installation des logiciels
  ###################################################################
    - name: Liste des paquets à installer
      set_fact:
        sw_list: "{{ software_map.get(departement, []) }}"

    - name: Installer Chocolatey
      win_chocolatey:
        name: chocolatey

    - name: Installer les paquets
      win_chocolatey:
        name: "{{ item }}"
        state: present
      loop: "{{ sw_list }}"
      when: sw_list | length > 0

  ###################################################################
  # 5) Mise à jour de l'inventaire
  ###################################################################
    - name: S’assurer de la section [ad_computers]
      lineinfile:
        path: "{{ inventaire_path }}"
        line: "[ad_computers]"
        state: present
        create: yes
      delegate_to: localhost
      connection: local
      run_once: true

    - name: Ajouter le FQDN si absent
      lineinfile:
        path: "{{ inventaire_path }}"
        line: "{{ new_fqdn }}"
        insertafter: "^\\[ad_computers\\]$"
        state: present
      when: new_fqdn not in inventaire_hostnames
      delegate_to: localhost
      connection: local
      run_once: true

    - debug:
        msg: "Inventaire mis à jour avec {{ new_fqdn }}"
      when: new_fqdn not in inventaire_hostnames
      run_once: true
      
    - name: Définir l'OU cible pour ce département
      set_fact:
        target_ou: "OU={{ departement }},OU=Bureau Computers,OU=Bureau,DC=fonteynethekitchen,DC=local"
    
    - name: Joindre le domaine dans l'OU spécifique
      win_domain_membership:
        dns_domain_name: "fonteynethekitchen.local"
        domain_admin_user: "{{ ldap_user }}"
        domain_admin_password: "{{ ldap_password }}"
        domain_ou_path: "{{ target_ou }}"
        hostname: "{{ ansible_hostname }}"
      register: domain_join
    
    - name: Redémarrer si nécessaire (join domaine)
      win_reboot:
      when: domain_join.reboot_required
