- name: Onboard poste Windows
  hosts: onboarding
  gather_facts: yes
  vars_prompt:
    - name: departement
      prompt: "Département (ex: IT, HR, FIN)"
      private: no

  vars:
    prefix_map:
      IT: "IT-"
      HR: "HR-"
      FIN: "FIN-"

  tasks:
    - name: Générer le nom dynamique
      set_fact:
        new_hostname: "{{ prefix_map[departement] }}{{ ansible_hostname | regex_replace('\\W+', '') | lower }}"

    - name: Afficher le nom qui sera appliqué
      debug:
        msg: "Nom d'hôte à appliquer : {{ new_hostname }}"

    - name: Renommer la machine
      ansible.windows.win_hostname:
        name: "{{ new_hostname }}"
      register: rename_result

    - name: Reboot si renommage effectué
      ansible.windows.win_reboot:
      when: rename_result.changed
