---
- name: Onboarding automatique depuis fichier texte
  hosts: onboarding
  gather_facts: yes

  vars:
    inventaire_path: "/tmp/semaphore/inventaire_ad.ini"
    prefix_map:
      IT:  "IT-LAPTOP"
      HR:  "HR-LAPTOP"
      FIN: "FIN-LAPTOP"
      COM: "COM-LAPTOP"

  tasks:
    # 1) Département
    - name: Lire le département
      ansible.windows.win_shell: Get-Content -Path 'C:\\departement.txt'
      register: departement_raw

    - name: Nettoyer le département
      set_fact:
        departement: "{{ departement_raw.stdout | trim }}"

    - name: Vérifier département
      fail:
        msg: "Département « {{ departement }} » non reconnu"
      when: departement not in prefix_map

    # 2) Charger inventaire une fois sur le contrôleur
    - name: Charger l'inventaire
      slurp:
        src: "{{ inventaire_path }}"
      register: inventaire_slurp
      ignore_errors: yes
      delegate_to: localhost
      vars:
        ansible_connection: local
      run_once: true

    - name: Stocker le contenu inventaire global
      set_fact:
        inventaire_content_b64_global: "{{ inventaire_slurp.content | default('') }}"
      delegate_to: localhost
      vars:
        ansible_connection: local
      run_once: true

    # 3) Calculer le prochain nom
    - name: Extraire les noms connus
      set_fact:
        existants: >-
          {{
            hostvars['localhost'].inventaire_content_b64_global
            | b64decode | split('\n')
            | reject('match', '^\[.*\]')
            | reject('equalto', '')
            | map('regex_replace', '\\..*$', '')
            | select('match', '^' ~ prefix_map[departement] ~ '-\\d{3}$')
            | list
          }}

    - name: Prochain ID libre
      set_fact:
        next_id: "{{ '%03d' % ((range(1,1000) | difference(existants | map('regex_replace','^.*-(\\d{3})$','\\1') | map('int'))) | min) }}"
        new_hostname: "{{ prefix_map[departement] }}-{{ next_id }}"

    - name: Afficher le nom généré
      debug:
        msg: "Nom à appliquer : {{ new_hostname }}"

    # 4) Renommer + reboot
    - name: Appliquer le nom
      ansible.windows.win_hostname:
        name: "{{ new_hostname }}"
      register: rename_result

    - name: Redémarrer si nécessaire
      ansible.windows.win_reboot:
      when: rename_result.changed

    # 5) Mettre à jour l'inventaire
    - name: Ajouter le nom dans l'inventaire
      copy:
        dest: "{{ inventaire_path }}"
        content: |
          [ad_computers]
          {% for name in (existants + [new_hostname]) | unique | sort %}
          {{ name }}.fonteynethekitchen.local
          {% endfor %}
      when: new_hostname not in existants
      delegate_to: localhost
      vars:
        ansible_connection: local
      run_once: true

    - name: Confirmation
      debug:
        msg: "Inventaire mis à jour avec {{ new_hostname }}"
      when: new_hostname not in existants
      run_once: true
