---
- name: Onboarding automatique depuis fichier texte
  hosts: onboarding
  gather_facts: yes

  vars:
    prefix_map:
      IT:  "IT-LAPTOP"
      HR:  "HR-LAPTOP"
      FIN: "FIN-LAPTOP"
      COM: "COM-LAPTOP"

  tasks:
    # 1) Lire et valider le département
    - name: Lire le département
      ansible.windows.win_shell: Get-Content -Path 'C:\\departement.txt'
      register: departement_raw

    - set_fact:
        departement: "{{ departement_raw.stdout | trim }}"

    - fail:
        msg: "Département « {{ departement }} » non reconnu"
      when: departement not in prefix_map

    # 2) Lire l’inventaire local et calculer le prochain ID
    - name: Récupérer le fichier d’inventaire
      slurp:
        src: "{{ inventaire_path }}"
      register: inventaire_slurp
      ignore_errors: yes
      delegate_to: localhost
      run_once: true

    - set_fact:
        inventaire_content_b64: "{{ inventaire_slurp.content | default('') }}"
        existants: >-
          {{
            inventaire_content_b64
            | b64decode | split('\n')
            | reject('match', '^\[.*\]')
            | reject('equalto', '')
            | map('regex_replace', '\\..*$', '')
            | select('match', '^' ~ prefix_map[departement] ~ '-\\d{3}$')
            | list
          }}

    - set_fact:
        next_id: "{{ '%03d' % ((range(1,1000) | difference(existants | map('regex_replace','^.*-(\\d{3})$','\\1') | map('int'))) | min) }}"
        new_hostname: "{{ prefix_map[departement] }}-{{ next_id }}"

    - name: Afficher le nom généré
      debug:
        msg: "Nom à appliquer : {{ new_hostname }}"

    # 3) Renommer + reboot
    - name: Appliquer le nom de machine
      ansible.windows.win_hostname:
        name: "{{ new_hostname }}"
      register: result

    - ansible.windows.win_reboot:
      when: result.changed

    # 4) Mettre à jour l’inventaire (localhost, une seule fois)
    - name: Ajouter le nom à l'inventaire
      copy:
        dest: "{{ inventaire_path }}"
        content: |
          [ad_computers]
          {% for name in (existants + [new_hostname]) | unique | sort %}
          {{ name }}.fonteynethekitchen.local
          {% endfor %}
      when: new_hostname not in existants
      delegate_to: localhost
      run_once: true

    - name: Confirmation inventaire
      debug:
        msg: "Inventaire mis à jour avec {{ new_hostname }}"
      when: new_hostname not in existants
      run_once: true
